### ISSUE TITLE
Copy-paste of keyframes is not working

### ISSUE THREAD

**Issue by villeilkkala** [TheMightyFingers/mightyeditor#47]
Copy-pasting keyframes no longer works. Tested online and locally with the latest version. Ctrl+C doesn't put anything to the clipping board.

**Comment by stauzs** [comment]
Fixed

**Comment by villeilkkala** [comment]
Thanks!

**Comment by villeilkkala** [comment]
I cloned the newest version and it seems that the bug happens again when running the editor locally. Online version works perfectly.

Error message says "Uncaught TypeError: Cannot set property metaKey of #<KeyboardEvent> which has only a getter" and errors at Events.js:232.

**Comment by stauzs** [comment]
actually that error started to appear with the chrome update to version 43. 
I have no idea why that error don't appear in the online version (probably chrome fails to scan so huge file).
I have fixed this in my local dev branch, but it's pretty useless at the moment, this error will be fixed with the next big update.

In the meantime you can use minified version locally: e.g. localhost/index.rel.html
or by running
./startprod
instead of ./startdev
